[project]
name = "ComfyUI_RIFE_TensorRT_RTX"
description = "Ultra fast frame interpolation using RIFE with TensorRT with Automatic downloading"
version = "0.1"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/ThreadsOfFate/ComfyUI-RIFE-TensorRT-RTX"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "ThreadsOfFate"
DisplayName = "ComfyUI_RIFE_TensorRT_RTX"
Icon = ""
